// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQT5nCS0NyFMVJFM7_i4J20MPETLYXNTA',
    appId: '1:421852152186:web:d5e1997cbe83e269d516c3',
    messagingSenderId: '421852152186',
    projectId: 'labcsa-f8e5d',
    authDomain: 'labcsa-f8e5d.firebaseapp.com',
    storageBucket: 'labcsa-f8e5d.appspot.com',
    measurementId: 'G-WWV7QCX3RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahbJyuRB8NcfXF3R9ZQwe1yR3bIYZ8lk',
    appId: '1:421852152186:android:2877a2fe2ca0aa77d516c3',
    messagingSenderId: '421852152186',
    projectId: 'labcsa-f8e5d',
    storageBucket: 'labcsa-f8e5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAq30gT71R_lxEaC3KmdlV1Hoz5cqH9qI',
    appId: '1:421852152186:ios:e676f8cfc84977fed516c3',
    messagingSenderId: '421852152186',
    projectId: 'labcsa-f8e5d',
    storageBucket: 'labcsa-f8e5d.appspot.com',
    iosBundleId: 'com.labfluttercsa.labfluttercsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAq30gT71R_lxEaC3KmdlV1Hoz5cqH9qI',
    appId: '1:421852152186:ios:f9f842525a66c9dbd516c3',
    messagingSenderId: '421852152186',
    projectId: 'labcsa-f8e5d',
    storageBucket: 'labcsa-f8e5d.appspot.com',
    iosBundleId: 'com.labfluttercsa.labfluttercsa.RunnerTests',
  );
}
